name: PR Title

on:
  pull_request:
    types: [opened, edited]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: deepakputhraya/action-pr-title@master
        name: Validate PR Title
        with:
          regex: '^(?<type>build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|\[Snyk\])(?<scope>\(\w+\)?((?=:\s)|(?=!:\s)))?(?<breaking>!)?(?<subject>:\s.*)?|^(?<merge>Merge \w+)' # Regex the title should match.
          allowed_prefixes: '[Snyk],feat,fix,docs,build,chore,ci,docs,style,refactor,pref,test' # title should start with the given prefix
          # disallowed_prefixes: 'feat/,hotfix' # title should not start with the given prefix
          max_length: 80 # Max length of the title
          github_token: ${{ github.token }}
